# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: replica.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'replica.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rreplica.proto\x12\x11messaging.replica\":\n\x16WriteOperationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"9\n\x13RegisterUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"(\n\x14\x44\x65leteAccountRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"\\\n\x14InsertMessageRequest\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x10\n\x08receiver\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t\"/\n\x1cMarkMessagesDeliveredRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"0\n\x19MarkMessagesAsReadRequest\x12\x13\n\x0bmessage_ids\x18\x01 \x03(\x05\"H\n\x19SetNUnreadMessagesRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x19\n\x11n_unread_messages\x18\x02 \x01(\x05\"*\n\x14\x44\x65leteMessageRequest\x12\x12\n\nmessage_id\x18\x01 \x01(\x05\x32\xf5\x05\n\x0eReplicaService\x12\x61\n\x0cRegisterUser\x12&.messaging.replica.RegisterUserRequest\x1a).messaging.replica.WriteOperationResponse\x12\x63\n\rDeleteAccount\x12\'.messaging.replica.DeleteAccountRequest\x1a).messaging.replica.WriteOperationResponse\x12\x63\n\rInsertMessage\x12\'.messaging.replica.InsertMessageRequest\x1a).messaging.replica.WriteOperationResponse\x12s\n\x15MarkMessagesDelivered\x12/.messaging.replica.MarkMessagesDeliveredRequest\x1a).messaging.replica.WriteOperationResponse\x12m\n\x12MarkMessagesAsRead\x12,.messaging.replica.MarkMessagesAsReadRequest\x1a).messaging.replica.WriteOperationResponse\x12m\n\x12SetNUnreadMessages\x12,.messaging.replica.SetNUnreadMessagesRequest\x1a).messaging.replica.WriteOperationResponse\x12\x63\n\rDeleteMessage\x12\'.messaging.replica.DeleteMessageRequest\x1a).messaging.replica.WriteOperationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'replica_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WRITEOPERATIONRESPONSE']._serialized_start=36
  _globals['_WRITEOPERATIONRESPONSE']._serialized_end=94
  _globals['_REGISTERUSERREQUEST']._serialized_start=96
  _globals['_REGISTERUSERREQUEST']._serialized_end=153
  _globals['_DELETEACCOUNTREQUEST']._serialized_start=155
  _globals['_DELETEACCOUNTREQUEST']._serialized_end=195
  _globals['_INSERTMESSAGEREQUEST']._serialized_start=197
  _globals['_INSERTMESSAGEREQUEST']._serialized_end=289
  _globals['_MARKMESSAGESDELIVEREDREQUEST']._serialized_start=291
  _globals['_MARKMESSAGESDELIVEREDREQUEST']._serialized_end=338
  _globals['_MARKMESSAGESASREADREQUEST']._serialized_start=340
  _globals['_MARKMESSAGESASREADREQUEST']._serialized_end=388
  _globals['_SETNUNREADMESSAGESREQUEST']._serialized_start=390
  _globals['_SETNUNREADMESSAGESREQUEST']._serialized_end=462
  _globals['_DELETEMESSAGEREQUEST']._serialized_start=464
  _globals['_DELETEMESSAGEREQUEST']._serialized_end=506
  _globals['_REPLICASERVICE']._serialized_start=509
  _globals['_REPLICASERVICE']._serialized_end=1266
# @@protoc_insertion_point(module_scope)
